server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://githubfast.com/manongshihao/orderingsystem-master.git #git仓库地址
          username: pjj #git仓库用户名
          password: 123456 #git仓库密码
          search-paths: config
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true